apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-autoscale
  labels:
    app: webk8s
    env: prod
    owner: Fakhri_Huseynov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kiev
  template:
    metadata:
      labels:
        project: kiev
    spec:
      containers:
        - name: kiev-web
          image: faxri/myk8s:version2
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta2v2
    kind: Deployment
    name: mywebapp-autoscale
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Pods
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
          value: resource
    - type: Pods
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
          value: resource