apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  labels:
    app: webk8s
spec:
  selector:
    matchLabels:
      project: baku1
  template:
    metadata:
      labels:
        project: baku1
    spec:
      containers:
        - name: baku-web1
          image: faxri/myapp:version2
          ports:
            - containerPort: 80
