apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-web-{{ .Release.Name }}
  labels:
    app:  my-app-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }} # Service will look for POD labels !!
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 80