apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdep03
  labels:
    app: mywebdep03-app
spec:
  selector:
    matchLabels:
      project: baku
  template:
    metadata:
      labels:
        project: baku # Service will look for those PODS labels !!!
    spec:
      containers:
        - name: baku-web
          image: faxri/myk8s:latest
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mywebdep-autoscale
spec:
  scaleTargetRef:
    kind: Deployment
    name: mywebdep03
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebdep-autoscale
  labels:
    env:   prod
    owner: Fakhri_Huseynov
spec:
  selector:
    project: baku            # Selecting PODS with those Labels
  ports:
    - name:       app-listener
      protocol:   TCP
      port:       80          # Port on Load Balancer
      targetPort: 80          # Port on POD
  type: LoadBalancer