apiVersion: v1
kind: Service
metadata:
  name: mywebdep-pod1
  labels:
    env:   prod
    owner: Fakhri_Huseynov
spec:
  selector:
    project: kiev            # Selecting PODS with those Labels
  ports:
    - name:       app-listener1
      protocol:   TCP
      port:       80          # Port on Load Balancer
      targetPort: 80          # Port on POD
  type: LoadBalancer